name: Python deploying

on: release

jobs:

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name }} == 'master'
    steps:
      # setup
#      - uses: actions/checkout@v3
#      - name: Set up Python 3.10
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.10'
#      # dependency's
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r setup/requirements.txt
      - name: echo
        run: echo 'deploying'
