name: Python package

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # dependency's
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r setup/requirements.txt
          pip install -r setup/requirements-testing.txt
      # testing
      - name: Test with pytest
        run: coverage run --source=app --branch -m unittest discover -v
      - name: Testing rapport
        run: python -m coverage xml
      # display report
      - name: Get Cover
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}



  deploy:
    runs-on: ubuntu-latest
    on:
      push: tags
    if: ${{ github.ref_name }} == 'master'
    steps:
      - name: echo
        run: echo 'deploying'
