name: Python on Release

on:
  release:
    types: created

jobs:
  testing:
    uses: ./.github/workflows/action_python_testing.yml

  linting:
    uses: ./.github/workflows/action_python_linting.yml

  sonar:
    uses: ./.github/workflows/action_sonarcloud.yml
    needs: [ testing ]
    secrets:
      github: ${{ secrets.GITHUB_TOKEN }}
      sonar: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: [testing, linting, sonar]
    steps:
      # setup
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # dependency's
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r config/requirements.txt
      - name: echo
        run: echo ${{ secrets.DEPLOY_TOKEN }}