name: Python Testing

on:
  pull_request:
    paths:
      - app/**
      - test/**
      - config/**
      - .pylint.rc

jobs:
  testing:
    uses: ./.github/workflows/action_python_testing.yml

  linting:
    uses: ./.github/workflows/action_python_linting.yml