name: Python on Push Master

on:
  push:
    branch: master


jobs:
  testing:
    uses: ./.github/workflows/action_python_testing.yml

  linting:
    uses: ./.github/workflows/action_python_linting.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [ testing, linting ]
    steps:
      # setup
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # dependency's
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r config/requirements.txt
      - name: echo
        run: echo 'deploying to staging with token ${{ secrets.DEPLOY_TOKEN }}'