name: Python Testing

on: [pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # dependency's
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./config/requirements.txt
          pip install -r config/requirements-testing.txt
      # testing
      - name: Test with pytest
        run: coverage run --source=app --branch -m unittest discover -v
      - name: Testing rapport
        run: python -m coverage xml
      # display report
      - name: Get Coverage
#        if: github.event_name == 'pull_request'
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}

  linting:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # dependency's
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./config/requirements.txt
          pip install -r config/requirements-linting.txt
      # Linting
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')