name: Python on Pull Request

on:
  pull_request:
    paths:
      - app/**
      - test/**
      - config/**
      - .pylintrc
      - .github/workflows/**

jobs:
  testing:
    uses: ./.github/workflows/action_python_testing.yml

  linting:
    uses: ./.github/workflows/action_python_linting.yml

  sonar:
    uses: ./.github/workflows/action_sonarcloud.yml
    secrets:
      github: ${{ secrets.GITHUB_TOKEN }}
      sonar: ${{ secrets.SONAR_TOKEN }}